inputs:
  key: {}
  restore-keys: {}
  path: {}
  enableCrossOsArchive:
    default: 'false'
runs:
  using: composite
  steps:
  - uses: actions/cache/restore@v4
    with:
      key: ${{ inputs.key }}
      restore-keys: ${{ inputs.restore-keys }}
      path: ${{ inputs.path }}
      enableCrossOsArchive: ${{ inputs.enableCrossOsArchive }}
      lookup-only: true
