on:
  workflow_call:
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repo
      uses: actions/checkout@v3
    - name: Update Dependencies
      run: npm update
    - name: Check cache is missing
      uses: ./
      with:
        key: mycachekey
        path: test
      id: check_cache_0
    - if: steps.check_cache_0.outputs.cache-hit == 'true'
      run: exit 1
    # - name: Upload cache
    # - name: Check cache is present
    #   uses: ./
    #   id: check_cache_0
    # - if: steps.check_cache_0.outputs.cache-hit != 'true'
    #   run: exit 1
    - name: Commit changes
      run: |
        # from https://github.com/orgs/community/discussions/26560
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git add .
        git commit -m "Update Dependencies"
        git push
      continue-on-error: true